[workspace]
resolver = "2"
members = [
    "benchmark",
    "programs/pinocchio",
    "programs/solana-nostd-entrypoint",
    "programs/solana-program"
]

[workspace.metadata.cli]
solana = "2.2.0"

[workspace.metadata.toolchains]
format = "1.84.1"
lint = "1.84.1"
