[package]
name = "eisodos-pinocchio"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.solana]
program-id = "Pinocchio1111111111111111111111111111111111"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
#pinocchio = { version="^0", features=["macro"], git="https://github.com/febo/pinocchio.git" }
pinocchio = { version="^0", features=["macro"], path="/Users/febo/Developer/febo/pinocchio/sdk" }
pinocchio-system = { version="^0", path="/Users/febo/Developer/febo/pinocchio/clients/system" }
