[package]
name = "eisodos-pinocchio"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.solana]
program-id = "Pinocchio1111111111111111111111111111111111"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = { version="0.2", git="https://github.com/febo/pinocchio.git" }
pinocchio-pubkey = { version="0.1", git="https://github.com/febo/pinocchio.git" }
pinocchio-system = { version="0.1", git="https://github.com/febo/pinocchio.git" }
