[package]
name = "eisodos-pinocchio"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.solana]
program-id = "Pinocchio1111111111111111111111111111111111"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.1"
pinocchio-pubkey = "0.1"
